# Generated by Django 5.2.14 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#111827', max_length=7)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7)),
                ('background_color', models.CharField(default='#f5f5f5', max_length=7)),
                ('text_color', models.CharField(default='#222222', max_length=7)),
                ('card_color', models.CharField(default='#ffffff', max_length=7)),
                ('public_title', models.CharField(blank=True, max_length=160)),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=120)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='company.companyprofile')),
            ],
            options={
                'verbose_name': 'branding',
                'verbose_name_plural': 'branding',
            },
        ),
    ]
