# Generated by Django 5.2.14 on 2026-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='border_color',
            field=models.CharField(default='#e5e7eb', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='default_item_image',
            field=models.ImageField(blank=True, upload_to='branding/defaults/'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='max_page_width',
            field=models.PositiveIntegerField(default=1180),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='muted_text_color',
            field=models.CharField(default='#64748b', max_length=7),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='rounded_corners',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='show_images_by_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='use_soft_shadows',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='background_color',
            field=models.CharField(default='#f8fafc', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='font_family',
            field=models.CharField(default='Inter, Arial, sans-serif', max_length=120),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='text_color',
            field=models.CharField(default='#172033', max_length=7),
        ),
    ]
