# Generated by Django 5.2.14 on 2026-05-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'voorraadlocatie',
                'verbose_name_plural': 'voorraadlocaties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('unit_type', models.CharField(choices=[('piece', 'Stuks'), ('weight', 'Gewicht'), ('volume', 'Volume'), ('length', 'Lengte'), ('package', 'Verpakking')], default='piece', max_length=30)),
                ('decimal_places', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'eenheid',
                'verbose_name_plural': 'eenheden',
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Voorraad erbij'), ('out', 'Voorraad eraf'), ('correction', 'Correctie'), ('waste', 'Verspilling'), ('sale', 'Verkoop'), ('purchase', 'Inkoop'), ('recipe_use', 'Receptverbruik')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voorraadmutatie',
                'verbose_name_plural': 'voorraadmutaties',
                'ordering': ['-created_at'],
            },
        ),
    ]
