# Generated by Django 5.2.14 on 2026-05-09 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Laat leeg om de vaste voorraadeenheid van het item te gebruiken.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Bijvoorbeeld gram als basiseenheid voor kilogram.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_units', to='inventory.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='factor_to_base',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Hoeveel basiseenheden zitten er in 1 van deze eenheid. 1 kg is 1000 gram.', max_digits=18),
        ),
    ]
