# Generated by Django 5.2.14 on 2026-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_unit_unit_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'permissions': [('can_adjust_stock', 'Kan voorraad opboeken en afboeken'), ('can_view_stock_dashboard', 'Kan voorraadbeheer bekijken')], 'verbose_name': 'voorraadmutatie', 'verbose_name_plural': 'voorraadmutaties'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason_code',
            field=models.CharField(choices=[('purchase', 'Inkoop'), ('sale', 'Verkoop'), ('manual_count', 'Handmatige telling'), ('correction_plus', 'Correctie erbij'), ('correction_minus', 'Correctie eraf'), ('waste', 'Derving'), ('expired', 'Over datum'), ('breakage', 'Breuk of schade'), ('donation', 'Donatie'), ('internal_use', 'Intern gebruik'), ('recipe_use', 'Verbruikt in recept'), ('return', 'Retour'), ('other', 'Overig')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Voorraad erbij'), ('out', 'Voorraad eraf'), ('correction', 'Correctie'), ('sale', 'Verkoop'), ('purchase', 'Inkoop'), ('recipe_use', 'Receptverbruik')], max_length=30),
        ),
    ]
