# Generated by Django 5.2.14 on 2026-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Voorraad erbij'), ('out', 'Voorraad eraf'), ('purchase', 'Inkoop'), ('sale', 'Verkoop'), ('recipe_use', 'Receptverbruik'), ('correction_in', 'Correctie erbij'), ('correction_out', 'Correctie eraf'), ('return', 'Retour erbij'), ('waste', 'Derving'), ('expired', 'Over datum'), ('breakage', 'Breuk of schade'), ('donation', 'Donatie'), ('internal_use', 'Intern gebruik')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason_code',
            field=models.CharField(choices=[('purchase', 'Inkoop'), ('sale', 'Verkoop'), ('manual_count_plus', 'Telling, erbij'), ('manual_count_minus', 'Telling, eraf'), ('correction_plus', 'Correctie erbij'), ('correction_minus', 'Correctie eraf'), ('waste', 'Derving'), ('expired', 'Over datum'), ('breakage', 'Breuk of schade'), ('donation', 'Donatie'), ('internal_use', 'Intern gebruik'), ('recipe_use', 'Verbruikt in recept'), ('return', 'Retour'), ('other', 'Overig')], default='other', max_length=40),
        ),
    ]
