# Generated by Django 5.2.14 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('output_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='items.item')),
            ],
            options={
                'verbose_name': 'recept',
                'verbose_name_plural': 'recepten',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='items.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'receptingrediënt',
                'verbose_name_plural': 'receptingrediënten',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
