# Generated by Django 5.2.14 on 2026-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Optionele ingrediënten blokkeren beschikbaarheid niet als ze op zijn.'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='note',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Aantal porties of verkoopitems waarvoor deze receptuur geldt.', max_digits=10),
        ),
    ]
