# Generated by Django 5.2.14 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('public_name', models.CharField(blank=True, max_length=160)),
                ('company_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('retail', 'Winkel'), ('storage', 'Opslag'), ('real_estate', 'Makelaar'), ('general', 'Algemeen bedrijf')], default='general', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bedrijfsprofiel',
                'verbose_name_plural': 'bedrijfsprofielen',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_inventory', models.BooleanField(default=True)),
                ('enable_recipes', models.BooleanField(default=True)),
                ('enable_orders', models.BooleanField(default=False)),
                ('enable_public_catalog', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=True)),
                ('require_stock_reason', models.BooleanField(default=True)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.companyprofile')),
            ],
            options={
                'verbose_name': 'bedrijfsinstelling',
                'verbose_name_plural': 'bedrijfsinstellingen',
            },
        ),
    ]
