# Generated by Django 5.2.14 on 2026-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='enable_featured_items',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enable_item_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enable_prices',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='show_public_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='show_public_labels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='show_public_prices',
            field=models.BooleanField(default=True),
        ),
    ]
