# Generated by Django 5.2.14 on 2026-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='show_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='use_default_image_when_missing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
