# Generated by Django 5.2.14 on 2026-05-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_short_description_item_show_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'permissions': [('can_manage_items', 'Kan items beheren')], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'itemmedia', 'verbose_name_plural': 'itemmedia'},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='caption',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='media_kind',
            field=models.CharField(choices=[('image', 'Afbeelding'), ('gif', 'Gif'), ('video', 'Video'), ('other', 'Overig')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='#e5e7eb', max_length=7),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('ingredient', 'Ingrediënt'), ('menu_item', 'Gerecht of menu-item'), ('product', 'Product'), ('drink', 'Drank'), ('asset', 'Bedrijfsmiddel'), ('property', 'Woning of pand'), ('service', 'Dienst'), ('storage_unit', 'Opslagobject')], default='product', max_length=40),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(upload_to='items/media/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='items.item'),
        ),
    ]
