# Generated by Django 5.2.14 on 2026-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'allergeen',
                'verbose_name_plural': 'allergenen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.allergen'),
        ),
    ]
